apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-exporter
  namespace: mail-stack
spec:
  selector:
    matchLabels:
      app: postfix-exporter
  template:
    metadata:
      labels:
        app: postfix-exporter
    spec:
      containers:
      - name: exporter
        image: kumina/postfix-exporter:v0.3.0
        ports:
        - containerPort: 9154
        args: ["--postfix.logfile_path=/var/log/mail.log"]
---
apiVersion: v1
kind: Service
metadata:
  name: postfix-exporter
  namespace: mail-stack
  labels:
    app: postfix-exporter
spec:
  ports:
  - port: 9154
    targetPort: 9154
  selector:
    app: postfix-exporter
