apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config
  namespace: mail-stack
data:
  dovecot.conf: |
    # =========================
    # LOGS
    # =========================
    log_path = /dev/stdout
    info_log_path = /dev/stdout

    auth_verbose = no
    auth_debug = no

    # =========================
    # PROTOCOLS
    # =========================
    protocols = imap pop3 lmtp

    listen = *

    disable_plaintext_auth = yes
    auth_mechanisms = plain login

    # =========================
    # MAIL LOCATION
    # =========================
    mail_location = maildir:/var/mail/%d/%n

    # =========================
    # AUTH SQL
    # =========================
    passdb {
      driver = sql
      args = /etc/dovecot/dovecot-sql.conf.ext
    }

    userdb {
      driver = sql
      args = /etc/dovecot/dovecot-sql.conf.ext
    }

    # =========================
    # TLS
    # =========================
    ssl = required
    ssl_cert = </etc/dovecot/ssl/tls.crt
    ssl_key = </etc/dovecot/ssl/tls.key
    ssl_min_protocol = TLSv1.2

    # =========================
    # LMTP
    # =========================
    service lmtp {
      inet_listener lmtp {
        port = 24
      }
    }

    # =========================
    # SASL (IMPORTANT FIX)
    # =========================
    service auth {
      unix_listener /var/spool/postfix/private/auth {
        mode = 0660
        user = postfix
        group = postfix
      }

      inet_listener {
        port = 10000
      }
    }

    # =========================
    # PERFORMANCE / LIMITS
    # =========================
    service imap-login {
      process_limit = 512
      client_limit = 50
    }

  dovecot-sql.conf.ext: |
    driver = mysql
    connect = host=mariadb-service.mail-stack.svc.cluster.local dbname=mailserver user=mailuser password=__DB_PASSWORD__

    default_pass_scheme = SHA512-CRYPT

    password_query = SELECT password FROM virtual_users WHERE email='%u' AND enabled=1;

    user_query = SELECT '/var/mail/%d/%n' AS home, 1000 AS uid, 1000 AS gid FROM virtual_users WHERE email='%u' AND enabled=1;
