apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: mail-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: clamav/clamav:latest
        # --- MODE MAINTENANCE : On force le pod à rester UP pour la copie ---
        #command: ["/bin/sh"]
        #args: ["-c", "sleep infinity"]
        # -------------------------------------------------------------------
        env:
        - name: CLAMAV_NO_FRESHCLAM_CHECK
          value: "true"
        - name: CLAMAV_NO_STARTUP_WAIT
          value: "true"
        ports:
        - containerPort: 3310
          name: clamd
        resources:
          limits:
            cpu: "1.5"
            memory: 4Gi
          requests:
            cpu: "500m"
            memory: 2Gi
        
        # StartupProbe : On laisse 10 min (60 * 10s) 
        # (Désactivée de fait par le sleep infinity, mais prête pour après)
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo PING | nc -w 5 localhost 3310 | grep PONG"
          failureThreshold: 60
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 15
          periodSeconds: 20

        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo PING | nc -w 5 localhost 3310 | grep PONG"
          initialDelaySeconds: 10
          periodSeconds: 10

        volumeMounts:
        - name: clamav-data
          mountPath: /var/lib/clamav

      volumes:
      - name: clamav-data
        persistentVolumeClaim:
          claimName: clamav-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clamav-service
  namespace: mail-stack
spec:
  selector:
    app: clamav
  ports:
    - port: 3310
      targetPort: 3310
