apiVersion: v1
kind: Service
metadata:
  name: rspamd-service
  namespace: mail-stack
spec:
  selector:
    app: rspamd
  ports:
    - name: milter
      protocol: TCP
      port: 11332
      targetPort: 11332
    - name: controller
      protocol: TCP
      port: 11334
      targetPort: 11334
