apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: mail-stack
data:
  main.cf: |
    compatibility_level = 3.6
    maillog_file = /dev/stdout

    # =========================
    # IDENTITY
    # =========================
    myhostname = mail.k8s.malagasy.com
    mydomain = k8s.malagasy.com
    myorigin = $mydomain

    inet_interfaces = all
    inet_protocols = ipv4

    # =========================
    # DESTINATION
    # =========================
    mydestination = localhost
    local_recipient_maps =

    # IMPORTANT : éviter trop large (10.0.0.0/8 supprimé)
    mynetworks = 127.0.0.0/8, 192.168.6.0/24, 10.244.0.0/16

    # =========================
    # RELAY SORTANT
    # =========================
    relayhost = [192.168.6.219]:587

    # =========================
    # ROUTAGE MAIL VIRTUEL
    # =========================
    virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
    virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
    virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf

    virtual_transport = lmtp:inet:dovecot-service.mail-stack.svc.cluster.local:24

    # =========================
    # SASL (DOVECOT OK)
    # =========================
    smtpd_sasl_auth_enable = yes
    smtpd_sasl_type = dovecot
    smtpd_sasl_path = dovecot-service.mail-stack.svc.cluster.local:10000
    smtpd_sasl_security_options = noanonymous
    smtpd_sasl_authenticated_header = yes

    # =========================
    # TLS
    # =========================
    smtpd_tls_security_level = may
    smtpd_tls_cert_file = /etc/postfix/tls.crt
    smtpd_tls_key_file = /etc/postfix/tls.key

    smtpd_tls_auth_only = yes

    # =========================
    # RSPAMD
    # =========================
    smtpd_milters = inet:rspamd-service.mail-stack.svc.cluster.local:11332
    non_smtpd_milters = inet:rspamd-service.mail-stack.svc.cluster.local:11332
    milter_default_action = accept

    # =========================
    # SECURITY
    # =========================
    smtpd_relay_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_unauth_destination

    smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_unauth_destination
