# k8s/mail/postfix/postfix-deployment.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postfix-pdb
  namespace: mail-stack
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: postfix
---
apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: mail-stack
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.6.221
  externalTrafficPolicy: Local # <--- CRITIQUE : Pour voir la vraie IP de l'attaquant
  ports:
    - {name: smtp, port: 25, targetPort: 25}
    - {name: submission, port: 587, targetPort: 587}
    - {name: smtps, port: 465, targetPort: 465}
  selector:
    app: postfix
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postfix
  namespace: mail-stack
spec:
  serviceName: postfix-service
  replicas: 3
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      initContainers:
        - name: init-postfix-config
          image: postfix-custom:v1
          command: ["sh", "-c"]
          args:
            - |
              cp -a /etc/postfix/* /mnt/config-prep/
              sed "s/__DB_PASSWORD__/$MYSQL_PASSWORD/g" /tmp/config-tpl/mysql-virtual-mailbox-domains.cf > /mnt/config-prep/mysql-virtual-mailbox-domains.cf
              sed "s/__DB_PASSWORD__/$MYSQL_PASSWORD/g" /tmp/config-tpl/mysql-virtual-mailbox-maps.cf > /mnt/config-prep/mysql-virtual-mailbox-maps.cf
              sed "s/__DB_PASSWORD__/$MYSQL_PASSWORD/g" /tmp/config-tpl/mysql-virtual-alias-maps.cf > /mnt/config-prep/mysql-virtual-alias-maps.cf
              cp /tmp/config-tpl/main.cf /mnt/config-prep/main.cf
              cp /tmp/config-tpl/master.cf /mnt/config-prep/master.cf
              # Désactiver chroot pour syslog
              sed -i '/^smtp/s/y/n/4' /mnt/config-prep/master.cf
              sed -i '/^submission/s/y/n/4' /mnt/config-prep/master.cf
              sed -i '/^smtps/s/y/n/4' /mnt/config-prep/master.cf
              cp /etc/resolv.conf /mnt/config-prep/resolv.conf
              cp /mnt/tls/tls.crt /mnt/config-prep/tls.crt
              cp /mnt/tls/tls.key /mnt/config-prep/tls.key
              chown -R root:root /mnt/config-prep
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: postfix-config-tpl
              mountPath: /tmp/config-tpl
            - name: postfix-config-final
              mountPath: /mnt/config-prep
            - name: postfix-tls
              mountPath: /mnt/tls
              readOnly: true
      containers:
        # CONTENEUR POSTFIX
        - name: postfix
          image: postfix-custom:v1
          env:
            - name: TZ
              value: "Indian/Antananarivo"
          volumeMounts:
            - name: postfix-config-final
              mountPath: /etc/postfix
            - name: postfix-queue
              mountPath: /var/spool/postfix
            - name: dev-log
              mountPath: /dev/log # Partagé avec le sidecar

        # SIDECAR : REDIRECTION VERS LE NAT
        - name: rsyslog-exporter
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache rsyslog
              echo "module(load=\"imuxsock\")" > /etc/rsyslog.conf
              echo "input(type=\"imuxsock\" socket=\"/dev/log\")" >> /etc/rsyslog.conf
              echo "*.* @192.168.6.219:514" >> /etc/rsyslog.conf
              rsyslogd -n
          volumeMounts:
            - name: dev-log
              mountPath: /dev/log

      volumes:
        - name: postfix-config-tpl
          configMap:
            name: postfix-config
        - name: postfix-config-final
          emptyDir: {}
        - name: dev-log
          emptyDir: {} # Socket Unix partagée
        - name: postfix-tls
          secret:
            secretName: mail-tls-prod-secret
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: postfix-queue
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn-mail
        resources:
          requests:
            storage: 2Gi
