apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
         
        # --- CONFIGURATION DES HÔTES LOCAUX ---
        hosts {
           # IMPORTANT: On pointe sur l'Ingress (.226) pour la validation HTTP-01
           192.168.6.226 mail.k8s.malagasy.com smtp.k8s.malagasy.com imap.k8s.malagasy.com webmail.k8s.malagasy.com
            
           # Services Monitoring
           192.168.6.224 grafana.malagasy.com
           192.168.6.225 prometheus.malagasy.com
            
           # Infrastructure & API
           192.168.6.123 k8s-api.malagasy.com longhorn.malagasy.com
            
           # Nœuds du Cluster
           192.168.6.114 k8s-master-1.malagasy.com
           192.168.6.118 k8s-master-2.malagasy.com
           192.168.6.124 k8s-master-3.malagasy.com
           192.168.6.117 k8s-worker-1.malagasy.com
           192.168.6.116 k8s-worker-2.malagasy.com
           192.168.6.115 k8s-worker-3.malagasy.com
            
           fallthrough
        }
        # --------------------------------------

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
